# Simple workflow for linting the open api definition
name: OpenAPI lint

on:
    push:
        paths: ["docs/**"]
    workflow_dispatch:

jobs:
    # single lint job since we are just linting
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.20'
            - name: Install vacuum
              run: go install github.com/daveshanley/vacuum@latest
            - name: Lint openapi definition file
              run: vacuum lint -dqs -p docs/static docs/static/openapi.json
